#!/usr/bin/env python3

from rnacounter import rnacounter
import docopt

if __name__ == '__main__':
    args = docopt.docopt(rnacounter.__doc__)
    if args['join']:
        rnacounter.join([args['TAB']]+args['TAB2'])
    else:
        bamname, annotname, options = rnacounter.parse_args(args)
        rnacounter.rnacounter_main(bamname,annotname, options)

