#!/usr/bin/env python3

try:
    from rnacounter import parse_args
    import rnacounter
except ImportError as e:
    try:
        from rnacounter.rnacounter import parse_args
        from rnacounter import rnacounter
    except ImportError as ee:
        from .rnacounter import rnacounter
import docopt

if __name__ == '__main__':
    args = docopt.docopt(rnacounter.usage_string())
    if args['join']:
        rnacounter.join([args['TAB']]+args['TAB2'])
    else:
        bamname, annotname, options = rnacounter.parse_args(args)
        rnacounter.rnacounter_main(bamname,annotname, options)

